---
- name: Check connectivity
  ping:
    data: alive
  tags: check

- name: update software
  apt: update_cache=yes
  become: true
  tags: update

# - name: Ensure Pip is installed.
#   package:
#     name: "{{ pip_package }}"
#     state: present

# - name: Ensure pip_install_packages are installed.
#   pip:
#     name: "{{ item.name | default(item) }}"
#     version: "{{ item.version | default(omit) }}"
#     virtualenv: "{{ item.virtualenv | default(omit) }}"
#     state: "{{ item.state | default(omit) }}"
#   with_items: "{{ pip_install_packages }}"
