xerberus_root_path: /opt/xerberus

xerberus_docker_compose_path: "{{ xerberus_root_path }}/xerberus_dc"

xerberus_dir_paths:
  - "{{ xerberus_root_path }}"
  - "{{ xerberus_root_path }}/scripts"
  - "{{ xerberus_docker_compose_path }}"

packages:
  - python3-pip
  - openssl # Required to generate tokens and certifcates

python_modules:
  - pip>=21.3.1 # pip must be the first module to be installed
  - pyopenssl
  - docker==6.1.3
  - docker-compose==1.29.2
  - urllib3<2
  - requests==2.32.1

# When enabled the role will install firewall package and add the required rules
enable_firewall: true

# when enable_firewall: true, ssh port will be allowed, override this variable if you use a custom port
ssh_port: 22

# Set to false to not allow SSH - you may be locked out of your server
allow_ssh: true

# By default ports exposed to host (i.e. expose_consensus_client_http_port_to_host) are bound to 127.0.0.1. This means that in order to access them
# from other hosts a reverse proxu or SSH tunnles must be used. If you want to access the ports without the need for reverse proxy
# set this variable to 0.0.0.0.
# NOTE: This should be used with caution and only when running behind a network firewall (or a secrutiy group).
# You should never change this on hosts directly exposed to the internet since the host firewall (firewalld or ufw)
# do not control access to ports managed by docker. For details see https://docs.docker.com/network/iptables/.
# See documenation for more details: TODO: link to our docs
host_ip_address_to_bind_to: 0.0.0.0

docker_image: "ghcr.io/xerberusteam/xerberus-node:full-node-latest"
container_name: "xerberus-full-node"
