version: "3.8"

services:
  bootnode:
    image: xerberus-node:latest
    container_name: bootnode
    volumes:
      - ../chain-spec-raw.json:/config/chain-spec-raw.json:ro
      - ../local-chain-state/data/bootnode:/data/bootnode
      - ../local-chain-state/keys/bootnode:/keys/bootnode:ro
    ports:
      - "30333:30333"
      - "9933:9933"
      - "9944:9944"
    environment:
      RUST_LOG: "afg=trace,grandpa=debug"
    command:
      - "--chain=/config/chain-spec-raw.json"
      - "--base-path=/data/bootnode"
      - "--node-key-file=/keys/bootnode/node-key"
      - "--listen-addr=/ip4/0.0.0.0/tcp/30333"
      - "--public-addr=/ip4/127.0.0.1/tcp/30333/p2p/12D3KooWPQJkTNMGQrjE9wTgGV98Ss5QEViorpysieDSTqS9ipri"
      - "--rpc-port=9933"
      - "--rpc-external"
      - "--rpc-methods=Unsafe"
      - "--rpc-cors=all"
      - "--allow-private-ip"
      - "--name=BootNode"

  validator1:
    image: xerberus-node:latest
    container_name: validator1
    depends_on:
      - bootnode
    volumes:
      - ../chain-spec-raw.json:/config/chain-spec-raw.json:ro
      - ../local-chain-state/data/validator1:/data/validator1
      - ../local-chain-state/keys/validator1:/keys/validator1:ro
    ports:
      - "30334:30333"
      - "9934:9933"
      - "9945:9944"
    environment:
      RUST_LOG: "afg=trace,grandpa=debug"
    command:
      - "--chain=/config/chain-spec-raw.json"
      - "--base-path=/data/validator1"
      - "--node-key-file=/keys/validator1/node-key"
      - "--port=30333"
      - "--rpc-port=9933"
      - "--rpc-external"
      - "--rpc-methods=Unsafe"
      - "--rpc-cors=all"
      - "--validator"
      - "--name=Validator1"
      - "--allow-private-ip"
      - "--bootnodes=/ip4/127.0.0.1/tcp/30333/p2p/12D3KooWPQJkTNMGQrjE9wTgGV98Ss5QEViorpysieDSTqS9ipri"

  validator2:
    image: xerberus-node:latest
    container_name: validator2
    depends_on:
      - bootnode
    volumes:
      - ../chain-spec-raw.json:/config/chain-spec-raw.json:ro
      - ../local-chain-state/data/validator2:/data/validator2
      - ../local-chain-state/keys/validator2:/keys/validator2:ro
    ports:
      - "30335:30333"
      - "9935:9933"
      - "9946:9944"
    environment:
      RUST_LOG: "afg=trace,grandpa=debug"
    command:
      - "--chain=/config/chain-spec-raw.json"
      - "--base-path=/data/validator2"
      - "--node-key-file=/keys/validator2/node-key"
      - "--port=30333"
      - "--rpc-port=9933"
      - "--rpc-external"
      - "--rpc-methods=Unsafe"
      - "--rpc-cors=all"
      - "--validator"
      - "--name=Validator2"
      - "--allow-private-ip"
      - "--bootnodes=/ip4/127.0.0.1/tcp/30333/p2p/12D3KooWPQJkTNMGQrjE9wTgGV98Ss5QEViorpysieDSTqS9ipri"

  validator3:
    image: xerberus-node:latest
    container_name: validator3
    depends_on:
      - bootnode
    volumes:
      - ../chain-spec-raw.json:/config/chain-spec-raw.json:ro
      - ../local-chain-state/data/validator3:/data/validator3
      - ../local-chain-state/keys/validator3:/keys/validator3:ro
    ports:
      - "30336:30333"
      - "9936:9933"
      - "9947:9944"
    environment:
      RUST_LOG: "afg=trace,grandpa=debug"
    command:
      - "--chain=/config/chain-spec-raw.json"
      - "--base-path=/data/validator3"
      - "--node-key-file=/keys/validator3/node-key"
      - "--port=30333"
      - "--rpc-port=9933"
      - "--rpc-external"
      - "--rpc-methods=Unsafe"
      - "--rpc-cors=all"
      - "--validator"
      - "--name=Validator3"
      - "--allow-private-ip"
      - "--bootnodes=/ip4/127.0.0.1/tcp/30333/p2p/12D3KooWPQJkTNMGQrjE9wTgGV98Ss5QEViorpysieDSTqS9ipri"

  lightnode:
    image: xerberus-node:latest
    container_name: lightnode
    depends_on:
      - bootnode
    volumes:
      - ../chain-spec-raw.json:/config/chain-spec-raw.json:ro
      - ../local-chain-state/data/lightnode:/data/lightnode
      - ../local-chain-state/keys/lightnode:/keys/lightnode:ro
    ports:
      - "30400:30333"
      - "9960:9933"
      - "9948:9944"
    environment:
      RUST_LOG: "afg=trace,grandpa=debug"
    command:
      - "--chain=/config/chain-spec-raw.json"
      - "--base-path=/data/lightnode"
      - "--node-key-file=/keys/lightnode/node-key"
      - "--port=30333"
      - "--rpc-port=9933"
      - "--rpc-external"
      - "--rpc-methods=Unsafe"
      - "--rpc-cors=all"
      - "--name=LightNode"
      - "--allow-private-ip"
      - "--bootnodes=/ip4/127.0.0.1/tcp/30333/p2p/12D3KooWPQJkTNMGQrjE9wTgGV98Ss5QEViorpysieDSTqS9ipri"

# =======================================================================================
# SETUP INSTRUCTIONS - Follow these steps in order
# =======================================================================================

# STEP 1: Generate P2P keys for all nodes
# ---------------------------------------
# subkey generate-node-key > local-chain-state/keys/bootnode/node-key
# subkey generate-node-key > local-chain-state/keys/validator1/node-key
# subkey generate-node-key > local-chain-state/keys/validator2/node-key
# subkey generate-node-key > local-chain-state/keys/validator3/node-key
# subkey generate-node-key > local-chain-state/keys/lightnode/node-key

# STEP 2: Generate Authority keys for validators
# ----------------------------------------------
# For each validator, you need to generate two types of keys:
# - Aura keys (Sr25519 scheme): Used for block production
# - GRANDPA keys (Ed25519 scheme): Used for block finalization
#
# Run these commands and save the output (mnemonic + public key):
# subkey generate --scheme Sr25519
# subkey generate --scheme Ed25519

# STEP 3: Create and customize the chain specification
# ---------------------------------------------------
# Generate the initial chain spec:
# ./target/release/solochain-template-node build-spec --chain local > chain-spec.json
#
# Edit chain-spec.json to add your validators' Aura and GRANDPA public keys
#
# Generate the raw chain spec:
# ./target/release/solochain-template-node build-spec --chain chain-spec.json --raw > chain-spec-raw.json

# STEP 4: Start the network
# ------------------------
# Launch all nodes:
# docker compose -f scripts/localnet.compose.yaml up -d
#
# Stop all nodes:
# docker compose -f scripts/localnet.compose.yaml down 

# STEP 5: Insert validator keys via RPC
# ------------------------------------
# For each validator, you need to insert the Aura and GRANDPA keys:

# Validator 1:
# Aura Key:
# curl -H "Content-Type: application/json" -d \
# '{"id":1,"jsonrpc":"2.0","method":"author_insertKey","params":["aura","ginger decrease bargain member learn business patch royal jacket company swamp tide","0x72a4fde8aeeab2fd90d577b588418eb0e175ef3f7984c10e11f887a2a158f07c"]}' \
# http://127.0.0.1:9934
#
# GRANDPA Key:
# curl -H "Content-Type: application/json" -d \
# '{"id":1,"jsonrpc":"2.0","method":"author_insertKey","params":["gran","park aerobic era zero sniff birth seven scorpion kite night axis name","0x4e558158a2afd092c7f655c2d63d210a36902ae76f7b124a44720f28063521c5"]}' \
# http://127.0.0.1:9934

# Validator 2:
# Aura Key:
# curl -H "Content-Type: application/json" -d \
# '{"id":1,"jsonrpc":"2.0","method":"author_insertKey","params":["aura","picnic dawn day sausage grunt flash endorse child under chaos fuel scorpion","0x96411bf7a592e11b8b86059fa7b2dc683d07b2217c650481198221bfc6ca3152"]}' \
# http://127.0.0.1:9935
#
# GRANDPA Key:
# curl -H "Content-Type: application/json" -d \
# '{"id":1,"jsonrpc":"2.0","method":"author_insertKey","params":["gran","basic inch decrease loyal always repair walnut minute carbon fashion addict bridge","0x7935ec050ad8b02d103bb0e7c30a60da0d93aa14baf119255f8c95a8310cb71f"]}' \
# http://127.0.0.1:9935

# Validator 3:
# Aura Key:
# curl -H "Content-Type: application/json" -d \
# '{"id":1,"jsonrpc":"2.0","method":"author_insertKey","params":["aura","monster brother winter uncle produce verify wet stomach strategy design route rotate","0x045885cbad88ff2539e9371833ec3ca2bd114bfdfdd34c869798e32340c65727"]}' \
# http://127.0.0.1:9936
#
# GRANDPA Key:
# curl -H "Content-Type: application/json" -d \
# '{"id":1,"jsonrpc":"2.0","method":"author_insertKey","params":["gran","luggage entry example old vivid addict swap skill electric chest drastic blouse","0x4b9667a0603960b40d17590c29ecc28bbc46614ba1246db45d2bd3b8b0852f5f"]}' \
# http://127.0.0.1:9936

# STEP 6: Connect to your network
# ------------------------------
# Access via Polkadot.js Apps:
# https://polkadot.js.org/apps/?rpc=ws://127.0.0.1:9944
# 
# All WebSocket endpoints:
# - Bootnode: ws://127.0.0.1:9944
# - Validator1: ws://127.0.0.1:9945
# - Validator2: ws://127.0.0.1:9946
# - Validator3: ws://127.0.0.1:9947
# - Lightnode: ws://127.0.0.1:9948
