---
- name: Deploy xerberus stack - whole stack per node
  hosts: xerberus
  become: true

  vars:
    pip_install_packages:
      - name: docker

  vars_files:
    - group_vars/all.yml
    - group_vars/xerberus.yml

  roles:
    - role: common
      # pip_install_packages:
      #   - "docker==6.1.3"
      #   - "docker-compose==1.29.2"
      #   - urllib3<2
      #   - requests==2.32.1
    - role: geerlingguy.docker
      vars:
        docker_package_state: present
        docker_install_compose_plugin: true
        docker_compose_package: docker-compose-plugin
        docker_compose_package_state: present
        docker_install_compose: true
        docker_service_manage: true
        # docker_add_repo: true
        docker_service_state: started
        docker_service_enabled: true
        docker_restart_handler_state: restarted
        docker_edition: 'ce'
        docker_packages:
          - 'docker-{{ docker_edition }}'
          - 'docker-{{ docker_edition }}-cli'
          - 'docker-{{ docker_edition }}-rootless-extras'
        docker_obsolete_packages:
          - docker
          - docker.io
          - docker-engine
          - podman-docker
          - containerd
          - runc
    - role: xerberus_compute
      vars:
        xerberus_root_path: /opt/xerberus
        xerberus_docker_compose_path: '{{ xerberus_root_path }}/xerberus_dc'
